blank_issues_enabled: false
contact_links:
  - name: Telegram Official Group
    url: https://t.me/StormBreakerOfficial
    about: Please ask and answer questions here.
  - name: Telegram Official Channel
    url: https://t.me/stormbreakerkernelupdatescl
    about: Our Official Telegram Channel
